### ISSUE TITLE
How to extend the settings, for e.g. to allow a different Chart type

### ISSUE THREAD

**Issue by papyr** [givanz/VvvebJs#162]
Hello, this is really a very very nice tool

Can you share some insights, in the settings, and I can help with adding more so it can be rolled into the Wiki for others.

1. How to how to extend `settings `to allwo user to select/switch/change the Graph type, for e.g. `Bar graph`
2. Allow user to _pick a data source for a table_, from a predefined list in a drop down, after dragging onto page.
3. Allow user to checkbox, auto generate ID's, for. e.g. I want to prepend `BudgetPage2-`_AutoIncrementedNumbers_ for the` div ID`

![image](https://user-images.githubusercontent.com/12733414/90340424-165e0300-dfc6-11ea-9387-9562d5b172ab.png)

**Comment by givanz** [comment]
Hi

Thank you, the chart type can be changed from content tab, the toolbar on the selected item is not intended to load/change element properties because of this to add this feature involves many changes to the code and is not a trivial change.

You can use the init method in widgets/chartjs component in libs/builder/components-widgets.js to make changes to the chart data set, currently the component gets the data from data-chart attribute from the component html, you can change it to fetch the data from other sources.

You can also prepend values to id from the same init method

```js	
	init: function (node)
	{
	   node.id = "BudgetPage" + Math.floor(Math.random()  * 100) + node.id;//vanilla style
	   jQuery(node).attr("id", "BudgetPage" + Math.floor(Math.random()  * 100) + node.id);//jquery style

		this.node = node;
		this.ctx = $("canvas", node).get(0).getContext("2d");
		this.config = JSON.parse(node.dataset.chart); // load from html attribute
        
               //load from json
                this.config = '{
			"type": "line",
			"labels": ["Red", "Blue", "Yellow", "Green", "Purple", "Orange"],
			"datasets": [{
				"data": [12, 19, 3, 5, 2, 3],
				"fill": false,
				"borderColor":"rgba(255, 99, 132, 0.2)"
			}, {
				"fill": false,
				"data": [3, 15, 7, 4, 19, 12],
				"borderColor": "rgba(54, 162, 235, 0.2)"
			}]
		};
		
		//load from server with ajax
		chart = this;
		$.get( "getchartdata.php", function( { myoption: "myvalue", myoption2: "myvalue2" } ) {
		  chart.config = data;
		  chart.drawChart();
		});
		

		return node;
	},
```
