### ISSUE TITLE
where is the location of the code editor so that the html tag in the head does not return to normal after editing?

### ISSUE THREAD

**Issue by wscdn** [givanz/VvvebJs#277]
hi sir, where is the code editor located so that the html tag in the head does not return to normal after editing?

**Comment by givanz** [comment]
Hi

The code editor uses Vvveb.Builder.setHtml https://github.com/givanz/VvvebJs/blob/master/libs/builder/builder.js#L1811 to update the page.

The setHtml function only updates body, it ignores `<head>` code because when updating `<head>` the browser will change the urls of `<style>` and `<script>` breaking the page.

**Comment by givanz** [comment]
Hi

In the last update https://github.com/givanz/VvvebJs/commit/8a462d946f8745eaa50be2ab3c64a987f669d7bd code editor also updates `<head>` changes.

**Comment by wscdn** [comment]
ok thank you sir work well. the problem is this will be much more effective for changes to css or js url paths and content that is installed in the head tag
