### ISSUE TITLE
How to make a host to host the resulting design

### ISSUE THREAD

**Issue by justinechacko** [givanz/VvvebJs#28]
Hi, 
I am a newbie. I would like to know after design How to create a webhost to host the resulting html website?

**Comment by givanz** [comment]
Hi

I added Vvveb.Gui.saveAjax method, to start using it edit editor.html and change

```
data-vvveb-action="save" 
```

to

```
data-vvveb-action="saveAjax" 
```

By default the ajax request is done to save.php url, you can change the url inside Vvveb.Gui.saveAjax  line 1171 inside builder.js 

A sample save.php is provided that will save the current page loaded through filemanager.

You only need to open the editor through a http server, it will not work if editor.html is opened directly from browser, and have php installed so that save.php can be called.

**Comment by oleteacher** [comment]
Just followed your above instructions and resulted in https://github.com/givanz/VvvebJs/issues/32

Also, there is no Vvveb.Gui.saveAjax line 1171 inside builder.js or jsut not seeing it:)

**Comment by givanz** [comment]
Sorry, I forgot to push all changes, please check again.

**Comment by oleteacher** [comment]
Works great now, thank you for your hard work!
