### ISSUE TITLE
Table column width does not update until unit is toggled

### ISSUE THREAD

**Issue by ashwinputhige** [givanz/VvvebJs#51]
1. Add a Table element
2. Click on TD. Go to Size. Increase width.
Issue: TD width does not change
3. Now change width unit from `px` to `em` to `px`. Change TD width. Notice that it works now.

**Comment by givanz** [comment]
Hi

Thanks for the bug report, I changed css input to also change on keypress and mouseup this will trigger change on all events.

Regarding TD elements sometimes depending on table parent container TD width can not be bigger, also when changing from px to % for example 100% can be a lot bigger than 100px and it can alter table display even if gradual changes like 105px can show no difference.

You can check with developer tools (F12 key in most browsers) and inspect the TD to see if the the width is changed (in style attribute) for the element and see if the issue is with the editor or that the element width can't be increased by the browser even if the editor changes the width.
