### ISSUE TITLE
Support Foundation?

### ISSUE THREAD

**Issue by dlewand691** [givanz/VvvebJs#9]
I use Foundation in most of my projects...how easy/difficult would it be to switch? Very intriguing project, for sure.

**Comment by givanz** [comment]
Hi

The builder can be used with any html/css framework bootstrap 4 components are provided because of popularity.

You can easily create a new component group just like bootstrap, you can read component docs here https://github.com/givanz/VvvebJs/wiki/Components also you can check existing components code like bootstrap in https://www.vvveb.com/vvvebjs/libs/builder/components-bootsrap4.js 

Most differences between boostrap and foundation from the library point of view of the editor components   are mostly class name differences, mostly you will just need to change boostrap 4 class names to foundation.

I made a very small demo for foundation https://www.vvveb.com/vvvebjs/editor-foundation.html 
you can further add new components using https://www.vvveb.com/vvvebjs/libs/builder/components-foundation.js
